// <auto-generated />
using System;
using DmsDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DmsDb.Migrations
{
    [DbContext(typeof(DmsDbContext))]
    [Migration("20251126174657_MakeRequiredOneToMany")]
    partial class MakeRequiredOneToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DmsDb.Entity.CommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DefectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DmsDb.Entity.DefectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EstateObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OriginalPosterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EstateObjectId");

                    b.HasIndex("OriginalPosterId");

                    b.ToTable("Defects");
                });

            modelBuilder.Entity("DmsDb.Entity.DefectImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DefectId");

                    b.ToTable("DefectImages");
                });

            modelBuilder.Entity("DmsDb.Entity.EstateObjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EstateObjects");
                });

            modelBuilder.Entity("DmsDb.Entity.EstateObjectImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EstateObjectEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EstateObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EstateObjectEntityId");

                    b.ToTable("EstateObjectImages");
                });

            modelBuilder.Entity("DmsDb.Entity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PfpPath")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Sex")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EstateObjectEntityUserEntity", b =>
                {
                    b.Property<Guid>("EstateObjectsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("EstateObjectsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("EstateObjectEntityUserEntity");
                });

            modelBuilder.Entity("DmsDb.Entity.DefectEntity", b =>
                {
                    b.HasOne("DmsDb.Entity.EstateObjectEntity", "EstateObject")
                        .WithMany("Defects")
                        .HasForeignKey("EstateObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmsDb.Entity.UserEntity", "OriginalPoster")
                        .WithMany("Defects")
                        .HasForeignKey("OriginalPosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstateObject");

                    b.Navigation("OriginalPoster");
                });

            modelBuilder.Entity("DmsDb.Entity.DefectImageEntity", b =>
                {
                    b.HasOne("DmsDb.Entity.DefectEntity", "Defect")
                        .WithMany("Images")
                        .HasForeignKey("DefectId");

                    b.Navigation("Defect");
                });

            modelBuilder.Entity("DmsDb.Entity.EstateObjectImageEntity", b =>
                {
                    b.HasOne("DmsDb.Entity.EstateObjectEntity", null)
                        .WithMany("Images")
                        .HasForeignKey("EstateObjectEntityId");
                });

            modelBuilder.Entity("EstateObjectEntityUserEntity", b =>
                {
                    b.HasOne("DmsDb.Entity.EstateObjectEntity", null)
                        .WithMany()
                        .HasForeignKey("EstateObjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmsDb.Entity.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DmsDb.Entity.DefectEntity", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("DmsDb.Entity.EstateObjectEntity", b =>
                {
                    b.Navigation("Defects");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("DmsDb.Entity.UserEntity", b =>
                {
                    b.Navigation("Defects");
                });
#pragma warning restore 612, 618
        }
    }
}
